reference_folder: /example/fastas/
genome_fasta: example.fasta
paired_reads_tags: ["_R1", "_R2"]
reads_extension: ".fastq"
callers : ["lumpy","delly2","cnvnator","pindel","cnproscan"]
reads_trimming: false

cnproscan_GC_normalization: TRUE
cnproscan_MAPPABILITY_normalization: TRUE
cnproscan_ORIC_normalization: TRUE
cnproscan_ORIC_POSITION: 1

procaryaSV_minCallers: 1
procaryaSV_min_sv_length: 1
procaryaSV_max_sv_length: NA
procaryaSV_maxGap: 2000

survivor_minCallers: 1
survivor_min_sv_length: 1
survivor_max_allowed_space: 1000

samples:
    - S01
    - S02
    - S03
    - S04
    - S05
    - S06
    - S07
    - S08
    - S09
    - S10
    - S11
