reference_folder: /home/rj/1TB/ProcaryaSV_K.pneumoniae/
genome_fasta: KP_ref.fasta
paired_reads_tags: ["_R1", "_R2"]
reads_extension: ".fastq"
callers : ["lumpy","delly2","cnvnator","pindel","cnproscan"]
reads_trimming: false
cnproscan_GC_normalization: TRUE
cnproscan_MAPPABILITY_normalization: TRUE
cnproscan_ORIC_normalization: TRUE
cnproscan_ORIC_POSITION: 
samples:
    - S01
    - S02
    - S03
    - S04
    - S05
    - S06
    - S07
    - S08
    - S09
    - S10
    - S11
    - S12
    - S13
    - S14
    - S15
    - S16
    - S17
    - S18
    - S19
    - S20
    - S21
    - S22
    - S23
    - S24
    - S25
    - S26
    - S27
    - S28
    - S29
    - S30
    - S31
    - S32
    - S33
    - S34
    - S35
    - S36
    - S37
    - S38
    - S39
    - S40
    - S41
    - S42
    - S43
    - S44
    - S45
    - S46
    - S47
    - S48
